name: "Hello Actions"
description: "Greet Someone"
author: "@balaganengg"

inputs:
  MY_NAME:
    description: "who to greet"
    required: true
    default: "World"
runs:
  using: "docker"
  image: "Dockerfile"
  
branding:
  icon: "mic"
  color: "purple"
